name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FluxGuard.sln

      - name: Build and publish CLI (self-contained)
        run: dotnet publish ./FluxGuard/FluxGuard.csproj -c Release -r win-x64 --self-contained true -o ./publish/cli

      - name: Build and publish GUI (self-contained)
        run: dotnet publish ./GUI/GUI.csproj -c Release -r win-x64 --self-contained true -o ./publish/gui

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: FluxGuard-CLI-win-x64
          path: ./publish/cli/

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: FluxGuard-GUI-win-x64
          path: ./publish/gui/
